import { ArrowLeft, CalendarDays, Mail, Pencil, Phone, WalletCards } from "lucide-react";
import { FormEvent, useState } from "react";
import { Modal, Shell, Status, Toast, Info, initials, money, pagePath, payments, residents } from "./_shared";

export default function ResidentDetail() {
  const params = new URLSearchParams(window.location.search);
  const residentId = Number(params.get("resident")) || 1;
  const resident = residents.find((item) => item.id === residentId) || residents[0];
  const history = payments.filter((payment) => payment.residentId === resident.id);
  const [showEdit, setShowEdit] = useState(false);
  const [name, setName] = useState(resident.name);
  const [toast, setToast] = useState("");
  const saveProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setShowEdit(false); setToast(`${name}'s profile was updated.`); };
  return <Shell active="Residents"><a href={pagePath("Residents")} className="rh-back"><ArrowLeft size={15} /> Resident directory</a><div className="rh-detail-head"><div className="rh-profile"><span className="rh-initials">{initials(resident.name)}</span><span><div className="rh-kicker">Resident profile</div><h1>{name}</h1><span className="rh-profile-meta"><Status value={resident.status} /><small className="rh-muted">{resident.home}</small></span></span></div><button className="rh-button secondary" onClick={() => setShowEdit(true)}><Pencil size={15} /> Edit profile</button></div>
    <div className="rh-grid" style={{ gridTemplateColumns: ".82fr 1.18fr", marginTop: 32 }}><section className="rh-grid"><div className="rh-card" style={{ padding: 23 }}><div className="rh-kicker">Contact</div><Info icon={Mail} label="Email" value={resident.email} /><Info icon={Phone} label="Phone" value={resident.phone} /><Info icon={CalendarDays} label="Moved in" value={resident.moveIn} /></div><div className="rh-card" style={{ padding: 23 }}><div className="rh-kicker">Notes for the team</div><p className="rh-note">{resident.notes}</p><div style={{ marginTop: 18, paddingTop: 15, borderTop: "1px solid var(--rh-line)", color: "var(--rh-muted)", fontSize: 11 }}>Keep the next conversation specific, kind, and documented.</div></div></section>
      <section className="rh-card" style={{ overflow: "hidden" }}><header className="rh-card-header" style={{ display: "flex", justifyContent: "space-between", gap: 15 }}><span><div className="rh-kicker">Financial record</div><h2>Payment history</h2></span><span style={{ textAlign: "right" }}><div className="rh-kicker">Current balance</div><strong style={{ display: "block", marginTop: 7, fontSize: 20 }}>{money(resident.balance)}</strong></span></header>{history.map((payment) => <div className="rh-row" key={payment.id}><span className="rh-initials" style={{ background: "#e3ebf2" }}><WalletCards size={16} /></span><span className="rh-row-content"><strong>{payment.date}</strong><small>{payment.method}</small></span><span style={{ textAlign: "right" }}><strong>{money(payment.amount)}</strong><br /><Status value={payment.status} /></span></div>)}{!history.length && <div className="rh-empty">No payment history yet.</div>}</section></div>
    {showEdit && <Modal title="Edit resident profile" description="Update the record while keeping the person behind it in view." onClose={() => setShowEdit(false)}><form className="rh-form-grid" onSubmit={saveProfile}><label>Full name<input className="rh-field" value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Team note<textarea className="rh-field" rows={3} defaultValue={resident.notes} style={{ height: "auto", paddingTop: 10 }} /></label><div className="rh-form-actions"><button type="button" className="rh-button secondary" onClick={() => setShowEdit(false)}>Cancel</button><button type="submit" className="rh-button"><Pencil size={15} /> Save changes</button></div></form></Modal>}{toast && <Toast message={toast} onDone={() => setToast("")} />}
  </Shell>;
}