// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/redeemer-branded/Dashboard.tsx": () => import("../components/mockups/redeemer-branded/Dashboard.tsx"),
  "./components/mockups/redeemer-branded/Payments.tsx": () => import("../components/mockups/redeemer-branded/Payments.tsx"),
  "./components/mockups/redeemer-branded/ResidentDetail.tsx": () => import("../components/mockups/redeemer-branded/ResidentDetail.tsx"),
  "./components/mockups/redeemer-branded/Residents.tsx": () => import("../components/mockups/redeemer-branded/Residents.tsx"),
  "./components/mockups/redeemer-current/Dashboard.tsx": () => import("../components/mockups/redeemer-current/Dashboard.tsx"),
  "./components/mockups/redeemer-current/Payments.tsx": () => import("../components/mockups/redeemer-current/Payments.tsx"),
  "./components/mockups/redeemer-current/ResidentDetail.tsx": () => import("../components/mockups/redeemer-current/ResidentDetail.tsx"),
  "./components/mockups/redeemer-current/Residents.tsx": () => import("../components/mockups/redeemer-current/Residents.tsx")
};
