import { ClipboardCheck, FileText, Home, Plus, RefreshCw, ShieldCheck, UsersRound } from 'lucide-react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AppShell } from '@/components/app-shell';
import { EmptyState, Field, Modal, QueryState, SelectField, SubmitButton, useDisclosure } from '@/components/ui-primitives';
import { useState } from 'react';

const get = async (path: string) => { const response = await fetch(`/api${path}`); if (!response.ok) throw new Error('Unable to load operations data'); return response.json(); };
const date = (value?: string) => value ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(new Date(value)) : 'Not scheduled';

export default function Operations() {
  const client = useQueryClient();
  const [section, setSection] = useState<'applications' | 'houses' | 'daily' | 'reports'>('applications');
  const applications = useQuery({ queryKey: ['/applications'], queryFn: () => get('/applications') });
  const houses = useQuery({ queryKey: ['/houses'], queryFn: () => get('/houses') });
  const daily = useQuery({ queryKey: ['/operations'], queryFn: () => get('/operations') });
  const reports = useQuery({ queryKey: ['/reports/summary'], queryFn: () => get('/reports/summary') });
  const active = section === 'applications' ? applications : section === 'houses' ? houses : section === 'daily' ? daily : reports;
  const modal = useDisclosure();
  return <AppShell><div className="animate-enter">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="section-kicker">ONEsource workspace</div><h1 data-testid="text-page-title" className="display-serif mt-2 text-4xl tracking-tight sm:text-5xl">Operations</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">One dependable place for intake, placement, daily care, and accountability across all four houses.</p></div><button onClick={() => client.invalidateQueries()} className="flex w-fit items-center gap-2 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-2.5 text-xs font-extrabold"><RefreshCw size={15} /> Refresh workspace</button></div>
    <div className="mt-8 grid gap-3 sm:grid-cols-4">{[
      ['applications', 'Applications', ClipboardCheck], ['houses', 'Houses & beds', Home], ['daily', 'Daily operations', ShieldCheck], ['reports', 'Reports', FileText],
    ].map(([value, label, Icon]) => <button key={String(value)} onClick={() => setSection(value as typeof section)} className={`flex items-center gap-3 rounded-2xl border p-4 text-left transition-colors ${section === value ? 'border-[hsl(var(--primary))] bg-[hsl(169_32%_87%/.55)]' : 'border-[hsl(var(--border))] bg-[hsl(var(--card))] hover:bg-[hsl(var(--secondary))]'}`}><Icon size={18} /><span className="text-xs font-extrabold">{String(label)}</span></button>)}</div>
    <QueryState loading={active.isLoading} error={active.isError} retry={() => active.refetch()}><div className="paper-card mt-6 overflow-hidden">
      {section === 'applications' && <Applications data={applications.data ?? []} onNew={modal.toggle} />}
      {section === 'houses' && <Houses data={houses.data ?? []} />}
      {section === 'daily' && <Daily data={daily.data ?? []} />}
      {section === 'reports' && <Reports data={reports.data} />}
    </div></QueryState>
    {modal.open && <ApplicationModal onClose={modal.close} onSaved={() => { modal.close(); client.invalidateQueries({ queryKey: ['/applications'] }); }} />}
  </div></AppShell>;
}

function Header({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="flex items-center justify-between border-b border-[hsl(var(--border))] px-6 py-5"><div><div className="section-kicker">{eyebrow}</div><h2 className="display-serif mt-1 text-2xl">{title}</h2></div>{action}</div>; }
function Applications({ data, onNew }: { data: any[]; onNew: () => void }) { return <><Header eyebrow="Admission pipeline" title="Applications" action={<button onClick={onNew} className="flex items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-3 py-2.5 text-xs font-extrabold text-white"><Plus size={15} /> New application</button>} />{data.length ? <div className="divide-y divide-[hsl(var(--border))]">{data.map((a) => <div key={a.id} className="flex flex-wrap items-center gap-4 px-6 py-4"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[hsl(169_32%_87%)] text-[hsl(var(--primary))]"><UsersRound size={16} /></div><div className="min-w-[180px] flex-1"><div className="text-sm font-extrabold">{a.applicantName}</div><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{a.email} · {date(a.createdAt)}</div></div><span className="rounded-full bg-[hsl(38_66%_88%)] px-2.5 py-1 text-[10px] font-extrabold uppercase">{a.status}</span></div>)}</div> : <div className="p-6"><EmptyState title="No applications yet" detail="Start an intake record to track requirements, waivers, referrals, and approval history." action={<button onClick={onNew} className="rounded-xl bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-extrabold text-white">Start intake</button>} /></div>}</>; }
function Houses({ data }: { data: any[] }) { return <><Header eyebrow="Capacity & placement" title="Houses and beds" />{data.length ? <div className="grid gap-4 p-6 md:grid-cols-2">{data.map((h) => <div key={h.id} className="rounded-2xl border border-[hsl(var(--border))] p-5"><div className="flex items-start justify-between"><div><div className="text-sm font-extrabold">{h.name}</div><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{h.address}</div></div><Home size={18} className="text-[hsl(var(--primary))]" /></div><div className="mt-6 flex items-end justify-between"><div><div className="section-kicker">Current residents</div><div className="mt-1 text-2xl font-extrabold">{h.occupancy}</div></div><div className="text-right"><div className="section-kicker">Family capacity</div><div className="mt-1 text-lg font-extrabold">{h.familyCapacity}</div></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className="h-full rounded-full bg-[hsl(var(--primary))]" style={{ width: `${Math.min((h.occupancy / Math.max(h.familyCapacity, 1)) * 100, 100)}%` }} /></div><div className="mt-3 text-xs text-[hsl(var(--muted-foreground))]">Individual ${h.individualWeekly}/week · Family ${h.familyWeekly}/week</div></div>)}</div> : <div className="p-6"><EmptyState title="No houses configured" detail="Add the four Redeemer House locations to begin assigning capacity." /></div>}</>; }
function Daily({ data }: { data: any[] }) { return <><Header eyebrow="Today & recurring" title="Daily operations" />{data.length ? <div className="divide-y divide-[hsl(var(--border))]">{data.map((o) => <div key={o.id} className="flex items-center gap-4 px-6 py-4"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[hsl(38_66%_88%)]"><ClipboardCheck size={16} /></div><div className="flex-1"><div className="text-sm font-extrabold">{o.title}</div><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{o.type} · {date(o.scheduledDate)}</div></div><span className="text-[10px] font-extrabold uppercase text-[hsl(var(--muted-foreground))]">{o.status}</span></div>)}</div> : <div className="p-6"><EmptyState title="The daily board is clear" detail="Randomized UAs, meetings, chores, milestones, incidents, and grievances will appear here." /></div>}</>; }
function Reports({ data }: { data?: any }) { return <><Header eyebrow="Administrator view" title="Reporting snapshot" /><div className="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-4">{[['Active residents', data?.occupancy?.active ?? 0], ['Collected', `$${data?.payments?.collected ?? 0}`], ['Overdue payments', data?.payments?.overdue ?? 0], ['Audit events', data?.auditEvents ?? 0]].map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-[hsl(var(--secondary)/.55)] p-4"><div className="section-kicker">{String(label)}</div><div className="mt-2 text-2xl font-extrabold">{String(value)}</div></div>)}</div><div className="px-6 pb-6 text-xs text-[hsl(var(--muted-foreground))]">Reports are administrator-only and every export is recorded in the audit history. CSV/PDF export can be enabled after the final report fields are approved.</div></>; }
function ApplicationModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ applicantName: '', email: '', phone: '', status: 'submitted', signedAcknowledgment: false, source: 'direct' }); const [saving, setSaving] = useState(false); const set = (k: keyof typeof form) => (v: string) => setForm((f) => ({ ...f, [k]: v })); const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); await fetch('/api/applications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setSaving(false); onSaved(); }; return <Modal title="Start an application" eyebrow="New intake" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Applicant name" name="application-name" value={form.applicantName} onChange={set('applicantName')} required placeholder="Full legal name" /><Field label="Email" name="application-email" value={form.email} onChange={set('email')} type="email" required placeholder="applicant@email.com" /><Field label="Phone" name="application-phone" value={form.phone} onChange={set('phone')} placeholder="(555) 000-0000" /><SelectField label="Source" name="application-source" value={form.source} onChange={set('source')} options={[{ value: 'direct', label: 'Direct inquiry' }, { value: 'referral', label: 'Referral partner' }, { value: 'one-step', label: 'One Step import' }]} /><label className="flex items-start gap-3 rounded-xl bg-[hsl(var(--secondary)/.5)] p-3 text-xs leading-relaxed"><input type="checkbox" checked={form.signedAcknowledgment} onChange={(e) => setForm((f) => ({ ...f, signedAcknowledgment: e.target.checked }))} required /> Applicant acknowledges the intake and consent statement.</label><div className="flex justify-end gap-3 border-t border-[hsl(var(--border))] pt-5"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-xs font-extrabold">Cancel</button><SubmitButton pending={saving}>Create application</SubmitButton></div></form></Modal>; }