import { ArrowUpRight, CheckCircle2, CreditCard, Plus, Search, WalletCards } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { getGetDashboardQueryKey, getListPaymentsQueryKey, useCreatePayment, useListPayments, useListResidents, type PaymentInput } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { EmptyState, Field, Modal, QueryState, SelectField, StatusBadge, SubmitButton, useDisclosure } from '@/components/ui-primitives';

const fmtDate = (v: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(v));
const money = (v: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(v);

export default function Payments() {
  const [status, setStatus] = useState('all');
  const [search, setSearch] = useState('');
  const modal = useDisclosure();
  const query = useListPayments({ status: status as 'all' | 'paid' | 'due' | 'overdue' });
  const filtered = useMemo(() => (query.data ?? []).filter((payment) => payment.residentName.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  const queryClient = useQueryClient();
  return <AppShell><div className="animate-enter">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="section-kicker">Money & accountability</div><h1 data-testid="text-page-title" className="display-serif mt-2 text-4xl tracking-tight sm:text-5xl">Payments</h1><p className="mt-3 text-sm text-[hsl(var(--muted-foreground))]">A simple pulse on what’s settled and what needs a conversation.</p></div><button data-testid="button-record-payment" onClick={modal.toggle} className="flex w-fit items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-xs font-extrabold text-[hsl(var(--primary-foreground))] transition-transform hover:-translate-y-0.5"><Plus size={16} /> Record payment</button></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><PulseCard label="Paid" value={(query.data ?? []).filter((x) => x.status === 'paid').reduce((s, x) => s + x.amount, 0)} tone="teal" /><PulseCard label="Due" value={(query.data ?? []).filter((x) => x.status === 'due').reduce((s, x) => s + x.amount, 0)} tone="sand" /><PulseCard label="Overdue" value={(query.data ?? []).filter((x) => x.status === 'overdue').reduce((s, x) => s + x.amount, 0)} tone="coral" /></div>
    <div className="paper-card mt-6 p-3 sm:p-4"><div className="flex flex-col gap-3 md:flex-row"><label className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-[hsl(var(--muted-foreground))]" /><span className="sr-only">Search payments</span><input data-testid="input-search-payments" type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Find a resident" className="h-11 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--card))] pl-10 pr-3 text-sm outline-none focus:border-[hsl(var(--primary))]" /></label><select data-testid="select-payment-status" value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--card))] px-3 text-sm font-semibold outline-none"><option value="all">All payments</option><option value="paid">Paid</option><option value="due">Due</option><option value="overdue">Overdue</option></select></div></div>
    <QueryState loading={query.isLoading} error={query.isError} retry={() => queryClient.invalidateQueries({ queryKey: getListPaymentsQueryKey() })}><div className="mt-6">{filtered.length ? <div className="paper-card overflow-hidden"><div className="hidden grid-cols-[1.5fr_1fr_1fr_1fr_auto] gap-4 border-b border-[hsl(var(--border))] px-5 py-3 text-[10px] font-extrabold uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))] md:grid"><div>Resident</div><div>Due date</div><div>Amount</div><div>Status</div><div /></div><div className="divide-y divide-[hsl(var(--border))]">{filtered.map((payment) => <div data-testid={`row-payment-${payment.id}`} key={payment.id} className="grid gap-3 px-5 py-4 transition-colors hover:bg-[hsl(var(--secondary)/.35)] md:grid-cols-[1.5fr_1fr_1fr_1fr_auto] md:items-center md:gap-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[hsl(var(--primary)/.1)] text-[hsl(var(--primary))]"><WalletCards size={16} /></div><div><Link href={`/residents/${payment.residentId}`} data-testid={`link-payment-resident-${payment.id}`} className="text-sm font-extrabold hover:text-[hsl(var(--primary))]">{payment.residentName}</Link><div className="mt-0.5 text-xs text-[hsl(var(--muted-foreground))]">{payment.method || 'Payment not recorded'}</div></div></div><div className="text-sm text-[hsl(var(--muted-foreground))]"><span className="mr-2 text-[10px] font-extrabold uppercase md:hidden">Due </span>{fmtDate(payment.dueDate)}</div><div className="text-sm font-extrabold">{money(payment.amount)}</div><div><StatusBadge status={payment.status} /></div><ArrowUpRight size={15} className="hidden text-[hsl(var(--muted-foreground))] md:block" /></div>)}</div></div> : <EmptyState title="No payments in this view" detail="When payments are added, their status and method will stay visible here." action={<button data-testid="button-empty-record-payment" onClick={modal.toggle} className="rounded-xl bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-extrabold text-[hsl(var(--primary-foreground))]">Record payment</button>} />}</div></QueryState>
    {modal.open && <PaymentModal onClose={modal.close} />}
  </div></AppShell>;
}

function PulseCard({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className={`paper-card flex items-center justify-between p-5 ${tone === 'teal' ? 'border-l-4 border-l-[hsl(var(--primary))]' : tone === 'sand' ? 'border-l-4 border-l-[hsl(38_66%_59%)]' : 'border-l-4 border-l-[hsl(var(--accent))]'}`}><div><div className="section-kicker">{label}</div><div className="mt-2 text-2xl font-extrabold">{money(value)}</div></div><CreditCard size={19} className="text-[hsl(var(--muted-foreground))]" /></div>; }

function PaymentModal({ onClose }: { onClose: () => void }) {
  const [form, setForm] = useState({ residentId: '', amount: '', dueDate: '', paidDate: new Date().toISOString().slice(0, 10), method: 'Bank transfer' });
  const residents = useListResidents({ status: 'active' });
  const create = useCreatePayment();
  const queryClient = useQueryClient();
  const set = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); const data: PaymentInput = { residentId: Number(form.residentId), amount: form.amount, dueDate: form.dueDate, paidDate: form.paidDate || undefined, method: form.method || undefined }; create.mutate({ data }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListPaymentsQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); onClose(); } }); };
  return <Modal title="Record a payment" eyebrow="Ledger entry" onClose={onClose}><form onSubmit={submit} className="space-y-4"><SelectField label="Resident" name="payment-resident" value={form.residentId} onChange={set('residentId')} options={[{ value: '', label: 'Select a resident' }, ...(residents.data ?? []).map((r) => ({ value: String(r.id), label: r.name }))]} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Amount" name="payment-amount" value={form.amount} onChange={set('amount')} type="number" min="0" step="0.01" required placeholder="0.00" /><Field label="Due date" name="payment-due-date" value={form.dueDate} onChange={set('dueDate')} type="date" required /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Paid date" name="payment-paid-date" value={form.paidDate} onChange={set('paidDate')} type="date" /><Field label="Method" name="payment-method" value={form.method} onChange={set('method')} placeholder="Bank transfer" /></div><div className="flex justify-end gap-3 border-t border-[hsl(var(--border))] pt-5"><button data-testid="button-cancel-form" type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-xs font-extrabold text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]">Cancel</button><SubmitButton pending={create.isPending}>Save payment</SubmitButton></div></form></Modal>;
}