import { Pencil, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { getGetDashboardQueryKey, getListResidentsQueryKey, useCreateResident, useListResidents, useUpdateResident, type Resident, type ResidentInput } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { EmptyState, Field, Modal, PageControls, QueryState, SelectField, StatusBadge, SubmitButton, useDisclosure } from '@/components/ui-primitives';

type ResidentForm = { name: string; email: string; phone: string; home: string; moveInDate: string; status: 'active' | 'pending' | 'exited'; notes: string };
const blank: ResidentForm = { name: '', email: '', phone: '', home: '', moveInDate: '', status: 'pending', notes: '' };
const fmtDate = (v: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(v));
const money = (v: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(v);
const PAGE_SIZE = 100;

export default function Residents() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const [offset, setOffset] = useState(0);
  const [hasMore, setHasMore] = useState(false);
  const modal = useDisclosure();
  const [editing, setEditing] = useState<Resident | null>(null);
  const params = { search: search || undefined, status: status as 'all' | 'active' | 'pending' | 'exited', limit: PAGE_SIZE, offset };
  const query = useListResidents(params, { request: { onResponse: (response) => setHasMore(response.headers.get('x-has-more') === 'true') } });
  const queryClient = useQueryClient();
  const openAdd = () => { setEditing(null); modal.setOpen(true); };
  const openEdit = (r: Resident) => { setEditing(r); modal.setOpen(true); };
  return <AppShell><div className="animate-enter">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="section-kicker">People & placements</div><h1 data-testid="text-page-title" className="display-serif mt-2 text-4xl tracking-tight sm:text-5xl">Residents</h1><p className="mt-3 text-sm text-[hsl(var(--muted-foreground))]">Keep every person’s next step visible.</p></div><button data-testid="button-add-resident" onClick={openAdd} className="flex w-fit items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-xs font-extrabold text-[hsl(var(--primary-foreground))] transition-transform hover:-translate-y-0.5"><Plus size={16} /> Add resident</button></div>
    <div className="paper-card mt-8 p-3 sm:p-4"><div className="flex flex-col gap-3 md:flex-row"><label className="relative flex-1"><span className="sr-only">Search residents</span><Search size={17} className="absolute left-3 top-3 text-[hsl(var(--muted-foreground))]" /><input data-testid="input-search-residents" type="search" value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} placeholder="Search by name, home, or email" className="h-11 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(42_37%_97%)] pl-10 pr-3 text-sm outline-none focus:border-[hsl(var(--primary))]" /></label><div className="flex items-center gap-2 text-xs font-bold text-[hsl(var(--muted-foreground))]"><SlidersHorizontal size={15} /><select data-testid="select-resident-status" value={status} onChange={(e) => { setStatus(e.target.value); setOffset(0); }} className="h-11 rounded-xl border border-[hsl(var(--input))] bg-[hsl(42_37%_97%)] px-3 text-sm font-semibold text-[hsl(var(--foreground))] outline-none"><option value="all">All statuses</option><option value="active">Active</option><option value="pending">Pending</option><option value="exited">Exited</option></select></div></div></div>
    <QueryState loading={query.isLoading} error={query.isError} retry={() => queryClient.invalidateQueries({ queryKey: getListResidentsQueryKey() })}><div className="mt-6">
      {query.data?.length || offset > 0 ? <div className="paper-card overflow-hidden"><div className="hidden grid-cols-[1.5fr_1fr_1fr_1fr_auto] gap-4 border-b border-[hsl(var(--border))] px-5 py-3 text-[10px] font-extrabold uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))] md:grid"><div>Resident</div><div>Home</div><div>Move-in</div><div>Balance</div><div /></div><div className="divide-y divide-[hsl(var(--border))]">{(query.data ?? []).map((resident) => <ResidentRow key={resident.id} resident={resident} onEdit={() => openEdit(resident)} />)}</div>{!query.data?.length && <div className="px-5 py-10 text-center text-sm text-[hsl(var(--muted-foreground))]">No residents on this page.</div>}<PageControls offset={offset} pageSize={PAGE_SIZE} hasMore={hasMore} onChange={setOffset} /></div> : <EmptyState title="No residents match that view" detail="Try a different name or status, or add someone new to the house." action={<button data-testid="button-empty-add-resident" onClick={openAdd} className="rounded-xl bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-extrabold text-[hsl(var(--primary-foreground))]">Add resident</button>} />}</div></QueryState>
    {modal.open && <ResidentModal resident={editing} onClose={modal.close} />}
  </div></AppShell>;
}

function ResidentRow({ resident, onEdit }: { resident: Resident; onEdit: () => void }) {
  return <div data-testid={`row-resident-${resident.id}`} className="grid gap-3 px-5 py-4 transition-colors hover:bg-[hsl(var(--secondary)/.35)] md:grid-cols-[1.5fr_1fr_1fr_1fr_auto] md:items-center md:gap-4"><Link href={`/residents/${resident.id}`} data-testid={`link-resident-${resident.id}`} className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[hsl(169_32%_87%)] text-xs font-extrabold text-[hsl(var(--primary))]">{resident.name.split(' ').map((n) => n[0]).join('').slice(0, 2)}</div><div className="min-w-0"><div className="truncate text-sm font-extrabold">{resident.name}</div><div className="mt-0.5 truncate text-xs text-[hsl(var(--muted-foreground))]">{resident.email}</div></div></Link><div className="flex items-center justify-between text-xs md:block"><span className="text-[hsl(var(--muted-foreground))] md:hidden">Home · </span><span className="font-semibold">{resident.home}</span><StatusBadge status={resident.status} /></div><div className="hidden text-xs text-[hsl(var(--muted-foreground))] md:block">{fmtDate(resident.moveInDate)}</div><div className="hidden text-sm font-extrabold md:block">{money(resident.balance)}</div><button data-testid={`button-edit-resident-${resident.id}`} onClick={onEdit} className="absolute right-5 top-6 text-[hsl(var(--muted-foreground))] transition-colors hover:text-[hsl(var(--primary))] md:static" aria-label={`Edit ${resident.name}`}><Pencil size={16} /></button></div>;
}

function ResidentModal({ resident, onClose }: { resident: Resident | null; onClose: () => void }) {
  const [form, setForm] = useState<ResidentForm>(resident ? { name: resident.name, email: resident.email, phone: resident.phone, home: resident.home, moveInDate: resident.moveInDate.slice(0, 10), status: resident.status, notes: resident.notes ?? '' } : blank);
  const create = useCreateResident();
  const update = useUpdateResident();
  const queryClient = useQueryClient();
  const pending = create.isPending || update.isPending;
  const set = (key: keyof ResidentForm) => (value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); const data: ResidentInput = { name: form.name, email: form.email, phone: form.phone, home: form.home, moveInDate: form.moveInDate, status: form.status, notes: form.notes || undefined }; const onSuccess = () => { queryClient.invalidateQueries({ queryKey: getListResidentsQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); onClose(); }; resident ? update.mutate({ id: resident.id, data }, { onSuccess }) : create.mutate({ data }, { onSuccess }); };
  return <Modal title={resident ? 'Edit resident' : 'Add a resident'} eyebrow={resident ? 'Update record' : 'New placement'} onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Full name" name="resident-name" value={form.name} onChange={set('name')} required placeholder="e.g. Jordan Lee" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Email" name="resident-email" value={form.email} onChange={set('email')} type="email" required placeholder="jordan@email.com" /><Field label="Phone" name="resident-phone" value={form.phone} onChange={set('phone')} required placeholder="(555) 000-0000" /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Home" name="resident-home" value={form.home} onChange={set('home')} required placeholder="Northside House" /><Field label="Move-in date" name="resident-move-in" value={form.moveInDate} onChange={set('moveInDate')} type="date" required /></div><SelectField label="Status" name="resident-status" value={form.status} onChange={set('status') as (value: string) => void} options={[{ value: 'pending', label: 'Pending' }, { value: 'active', label: 'Active' }, { value: 'exited', label: 'Exited' }]} /><label className="block"><span className="mb-1.5 block text-[11px] font-extrabold uppercase tracking-[.08em] text-[hsl(var(--muted-foreground))]">Notes</span><textarea data-testid="input-resident-notes" value={form.notes} onChange={(e) => setForm((current) => ({ ...current, notes: e.target.value }))} rows={3} placeholder="Anything the team should keep in view" className="w-full resize-none rounded-xl border border-[hsl(var(--input))] bg-[hsl(42_37%_97%)] px-3 py-2.5 text-sm outline-none focus:border-[hsl(var(--primary))]" /></label><div className="flex justify-end gap-3 border-t border-[hsl(var(--border))] pt-5"><button data-testid="button-cancel-form" type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-xs font-extrabold text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]">Cancel</button><SubmitButton pending={pending}>{resident ? 'Save changes' : 'Add resident'}</SubmitButton></div></form></Modal>;
}